//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class configuration {
    
    private string wSUsernameField;
    
    private string wSPasswordField;
    
    private bool wSPasswordEncryptedField;
    
    private bool servicesEnabledField;
    
    private int serverPortField;
    
    private string motion_WSActivity_iSpyField;
    
    private bool enable_Error_ReportingField;

    private bool is_silent_startup_CheckField;

    private bool enable_Update_CheckField;
    
    private string password_Protect_PasswordField;
    
    private bool enable_Password_ProtectField;
    
    private bool password_Protect_StartupField;
    
    private string mJPEGURLField;
    
    private string aVIFileNameField;
    
    private string recentJPGListField;
    
    private string recentMJPGListField;
    
    private string recentFileListField;
    
    private bool subscribedField;
    
    private string jPEGURLField;
    
    private string activityColorField;
    
    private string noActivityColorField;
    
    private string trackingColorField;
    
    private string floorPlanHighlightColorField;
    
    private string volumeLevelColorField;
    
    private int maxRecordingThreadsField;
    
    private string mainColorField;
    
    private string areaColorField;
    
    private string backColorField;
    
    private int maxMediaFolderSizeMBField;
    
    private int deleteFilesOlderThanDaysField;
    
    private string serverAddressField;
    
    private bool enabled_ShowGettingStartedField;
    
    private int opacityField;
    
    private int lANPortField;
    
    private bool enable_Storage_ManagementField;
    
    private string fFMPEG_CameraField;
    
    private string fFMPEG_MicrophoneField;
    
    private string timestampColorField;
    
    private string borderHighlightColorField;
    
    private string borderDefaultColorField;
    
    private bool useUPNPField;
    
    private string youTubeUsernameField;
    
    private string youTubePasswordField;
    
    private string youTubeAccountField;
    
    private string youTubeKeyField;
    
    private string youTubeCategoriesField;
    
    private string youTubeDefaultCategoryField;
    
    private string youTubeTokenField;
    
    private string compressorOptionsField;
    
    private bool logFFMPEGCommandsField;
    
    private bool balloonTipsField;
    
    private string trayIconTextField;
    
    private bool autoLayoutField;
    
    private string upnpDeviceField;
    
    private string iPModeField;
    
    private string iPv4AddressField;
    
    private string iPv6AddressField;
    
    private bool specificIPField;
    
    private bool dHCPRerouteField;
    
    private string mediaDirectoryField;
    
    private bool fFMPEG_SingleProcessField;
    
    private bool loopbackField;
    
    private int serverReceiveTimeoutField;
    
    private int iPCameraTimeoutField;
    
    private string serverNameField;
    
    private string uploadedVideosField;
    
    private string languageField;
    
    private string recentVLCListField;
    
    private string vLCURLField;
    
    private string vLCLocationField;
    
    private bool autoScheduleField;
    
    private bool fullscreenField;
    
    private bool showStatusField;
    
    private bool showToolbarField;
    
    private bool showFileMenuField;
    
    private bool alwaysOnTopField;
    
    private int logFileSizeKBField;
    
    private int cPUMaxField;
    
    private string allowedIPListField;
    
    private string resellerField;
    
    private bool createAlertWindowsField;
    
    private int maxRedrawRateField;
    
    private int previewItemsField;
    
    private bool showOverlayControlsField;
    
    private bool showMediaPanelField;
    
    private int priorityField;
    
    private bool monitorField;
    
    private int runTimesField;
    
    private bool screensaverWakeupField;
    
    private string vendorField;
    
    private string talkMicField;
    
    private int playbackModeField;
    
    private int jPEGQualityField;
    
    private bool stopSavingOnStorageLimitField;
    
    private bool viewControllerField;
    
    private int layoutModeField;
    
    private bool showPTZControllerField;

    private bool showPTZCommandButtonsField;

    private bool bigButtonsField;
    
    private bool lockLayoutField;
    
    private string mediaPanelSizeField;
    
    private bool minimiseOnCloseField;
    
    private bool iPv6DisabledField;
    
    private bool deleteToRecycleBinField;
    
    private bool speechRecognitionField;
    
    private string defaultManufacturerField;
    
    private string appendLinkTextField;
    
    private string startupFormField;
    
    private bool trayOnMinimiseField;
    
    private bool enableGZipField;
    
    private long featureSetField;
    
    private int mJPEGStreamIntervalField;
    
    private string alertOnDisconnectField;
    
    private string alertOnReconnectField;
    
    private int startupModeField;
    
    private int disconnectNotificationDelayField;
    
    private string archiveField;
    
    private string archiveNewField;
    
    private string mailAlertSubjectField;
    
    private string mailAlertBodyField;
    
    private string sMSAlertField;
    
    private string sMTPFromAddressField;
    
    private string sMTPUsernameField;
    
    private string sMTPPasswordField;
    
    private string sMTPServerField;
    
    private int sMTPPortField;
    
    private bool useSMTPField;
    
    private bool sMTPSSLField;
    
    private bool defaultRecordOnAlertField;
    
    private bool defaultRecordOnDetectField;
    
    private bool firstRunField;
    
    private string deviceDriverDefaultField;
    
    private string sSLCertificateField;
    
    private bool sSLClientRequiredField;
    
    private bool sSLIgnoreErrorsField;
    
    private bool sSLCheckRevocationField;
    
    private bool sSLEnabledField;
    
    private string googleDriveConfigField;
    
    private string dropBoxConfigField;
    
    private bool openGrabsField;
    
    private string textSentencesField;
    
    private string playPathsField;
    
    private int vLCFileCacheField;
    
    private string referersField;
    
    private string encryptCodeField;
    
    private string tagsField;
    
    private int portMapperModeField;
    
    private int arrangeModeField;
    
    private string brandPathField;

    private int commandButtonsLocationX;

    private int commandButtonsLocationY;

    private int commandButtonsWidth;

    private int commandButtonsHeight;

    private configurationGPU gPUField;
    
    private configurationLogging loggingField;
    
    private configurationCloud cloudField;
    
    private configurationServer[] fTPServersField;
    
    private configurationGrid[] gridViewsField;
    
    private configurationJoystick joystickField;
    
    private configurationDirectory[] mediaDirectoriesField;
    
    private configurationGroup[] permissionsField;
    
    private string chosenGroupNameField;

    public configuration() {
        this.wSPasswordEncryptedField = false;
        this.maxRecordingThreadsField = 4;
        this.useUPNPField = true;
        this.specificIPField = false;
        this.dHCPRerouteField = true;
        this.mediaDirectoryField = "NotSet";
        this.vLCLocationField = "";
        this.cPUMaxField = 90;
        this.allowedIPListField = "";
        this.resellerField = "";
        this.createAlertWindowsField = true;
        this.maxRedrawRateField = 10;
        this.previewItemsField = 100;
        this.showOverlayControlsField = true;
        this.showMediaPanelField = true;
        this.priorityField = 3;
        this.monitorField = true;
        this.runTimesField = 0;
        this.screensaverWakeupField = false;
        this.vendorField = "";
        this.talkMicField = "";
        this.playbackModeField = 0;
        this.jPEGQualityField = 75;
        this.stopSavingOnStorageLimitField = false;
        this.viewControllerField = true;
        this.layoutModeField = 0;
        this.showPTZControllerField = false;
        this.showPTZCommandButtonsField = false;
        this.bigButtonsField = false;
        this.lockLayoutField = false;
        this.mediaPanelSizeField = "";
        this.minimiseOnCloseField = false;
        this.iPv6DisabledField = false;
        this.deleteToRecycleBinField = false;
        this.speechRecognitionField = false;
        this.startupFormField = "iSpy";
        this.trayOnMinimiseField = true;
        this.enableGZipField = true;
        this.featureSetField = ((long)(0));
        this.mJPEGStreamIntervalField = 100;
        this.alertOnDisconnectField = "";
        this.alertOnReconnectField = "";
        this.startupModeField = 0;
        this.disconnectNotificationDelayField = 60;
        this.archiveField = "";
        this.archiveNewField = "";
        this.mailAlertSubjectField = "[EVENT]: [SERVER] [OBJECTNAME]";
        this.mailAlertBodyField = "[EVENT] at [DATE] [TIME]: [SERVER] [OBJECTNAME] [RECORDED] [PLUGIN]";
        this.sMSAlertField = "[EVENT] at [DATE] [TIME]: [SERVER] [OBJECTNAME] [RECORDED] [PLUGIN]";
        this.sMTPFromAddressField = "";
        this.sMTPUsernameField = "";
        this.sMTPPasswordField = "";
        this.sMTPServerField = "";
        this.sMTPPortField = 25;
        this.useSMTPField = false;
        this.sMTPSSLField = false;
        this.defaultRecordOnAlertField = false;
        this.defaultRecordOnDetectField = true;
        this.firstRunField = true;
        this.deviceDriverDefaultField = "";
        this.sSLCertificateField = "";
        this.sSLClientRequiredField = false;
        this.sSLIgnoreErrorsField = true;
        this.sSLCheckRevocationField = true;
        this.sSLEnabledField = false;
        this.googleDriveConfigField = "";
        this.dropBoxConfigField = "";
        this.openGrabsField = true;
        this.textSentencesField = "";
        this.playPathsField = "";
        this.vLCFileCacheField = 3000;
        this.referersField = "";
        this.encryptCodeField = "";
        this.tagsField = "";
        this.portMapperModeField = 2;
        this.arrangeModeField = 0;
        this.brandPathField = "";
        this.commandButtonsLocationX = -1;
        this.commandButtonsLocationY = -1;
    }

    /// <remarks/>
    public int CommandButtonsHeight
    {
        get
        {
            return this.commandButtonsHeight;
        }
        set
        {
            this.commandButtonsHeight = value;
        }
    }


    /// <remarks/>
    public int CommandButtonsWidth
    {
        get
        {
            return this.commandButtonsWidth;
        }
        set
        {
            this.commandButtonsWidth = value;
        }
    }

    /// <remarks/>
    public int CommandButtonsLocationX
    {
        get
        {
            return this.commandButtonsLocationX;
        }
        set
        {
            this.commandButtonsLocationX = value;
        }
    }

    /// <remarks/>
    public int CommandButtonsLocationY
    {
        get
        {
            return this.commandButtonsLocationY;
        }
        set
        {
            this.commandButtonsLocationY = value;
        }
    }

    /// <remarks/>
    public string WSUsername {
        get {
            return this.wSUsernameField;
        }
        set {
            this.wSUsernameField = value;
        }
    }
    
    /// <remarks/>
    public string WSPassword {
        get {
            return this.wSPasswordField;
        }
        set {
            this.wSPasswordField = value;
        }
    }
    
    /// <remarks/>
    public bool WSPasswordEncrypted {
        get {
            return this.wSPasswordEncryptedField;
        }
        set {
            this.wSPasswordEncryptedField = value;
        }
    }
    
    /// <remarks/>
    public bool ServicesEnabled {
        get {
            return this.servicesEnabledField;
        }
        set {
            this.servicesEnabledField = value;
        }
    }
    
    /// <remarks/>
    public int ServerPort {
        get {
            return this.serverPortField;
        }
        set {
            this.serverPortField = value;
        }
    }
    
    /// <remarks/>
    public string motion_WSActivity_iSpy {
        get {
            return this.motion_WSActivity_iSpyField;
        }
        set {
            this.motion_WSActivity_iSpyField = value;
        }
    }
    
    /// <remarks/>
    public bool Enable_Error_Reporting {
        get {
            return this.enable_Error_ReportingField;
        }
        set {
            this.enable_Error_ReportingField = value;
        }
    }

    /// <remarks/>
    public bool Is_Silent_Startup_Check
    {
        get
        {
            return this.is_silent_startup_CheckField;
        }
        set
        {
            this.is_silent_startup_CheckField = value;
        }
    }

    /// <remarks/>
    public bool Enable_Update_Check {
        get {
            return this.enable_Update_CheckField;
        }
        set {
            this.enable_Update_CheckField = value;
        }
    }
    
    /// <remarks/>
    public string Password_Protect_Password {
        get {
            return this.password_Protect_PasswordField;
        }
        set {
            this.password_Protect_PasswordField = value;
        }
    }
    
    /// <remarks/>
    public bool Enable_Password_Protect {
        get {
            return this.enable_Password_ProtectField;
        }
        set {
            this.enable_Password_ProtectField = value;
        }
    }
    
    /// <remarks/>
    public bool Password_Protect_Startup {
        get {
            return this.password_Protect_StartupField;
        }
        set {
            this.password_Protect_StartupField = value;
        }
    }
    
    /// <remarks/>
    public string MJPEGURL {
        get {
            return this.mJPEGURLField;
        }
        set {
            this.mJPEGURLField = value;
        }
    }
    
    /// <remarks/>
    public string AVIFileName {
        get {
            return this.aVIFileNameField;
        }
        set {
            this.aVIFileNameField = value;
        }
    }
    
    /// <remarks/>
    public string RecentJPGList {
        get {
            return this.recentJPGListField;
        }
        set {
            this.recentJPGListField = value;
        }
    }
    
    /// <remarks/>
    public string RecentMJPGList {
        get {
            return this.recentMJPGListField;
        }
        set {
            this.recentMJPGListField = value;
        }
    }
    
    /// <remarks/>
    public string RecentFileList {
        get {
            return this.recentFileListField;
        }
        set {
            this.recentFileListField = value;
        }
    }
    
    /// <remarks/>
    public bool Subscribed {
        get {
            return this.subscribedField;
        }
        set {
            this.subscribedField = value;
        }
    }
    
    /// <remarks/>
    public string JPEGURL {
        get {
            return this.jPEGURLField;
        }
        set {
            this.jPEGURLField = value;
        }
    }
    
    /// <remarks/>
    public string ActivityColor {
        get {
            return this.activityColorField;
        }
        set {
            this.activityColorField = value;
        }
    }
    
    /// <remarks/>
    public string NoActivityColor {
        get {
            return this.noActivityColorField;
        }
        set {
            this.noActivityColorField = value;
        }
    }
    
    /// <remarks/>
    public string TrackingColor {
        get {
            return this.trackingColorField;
        }
        set {
            this.trackingColorField = value;
        }
    }
    
    /// <remarks/>
    public string FloorPlanHighlightColor {
        get {
            return this.floorPlanHighlightColorField;
        }
        set {
            this.floorPlanHighlightColorField = value;
        }
    }
    
    /// <remarks/>
    public string VolumeLevelColor {
        get {
            return this.volumeLevelColorField;
        }
        set {
            this.volumeLevelColorField = value;
        }
    }
    
    /// <remarks/>
    public int MaxRecordingThreads {
        get {
            return this.maxRecordingThreadsField;
        }
        set {
            this.maxRecordingThreadsField = value;
        }
    }
    
    /// <remarks/>
    public string MainColor {
        get {
            return this.mainColorField;
        }
        set {
            this.mainColorField = value;
        }
    }
    
    /// <remarks/>
    public string AreaColor {
        get {
            return this.areaColorField;
        }
        set {
            this.areaColorField = value;
        }
    }
    
    /// <remarks/>
    public string BackColor {
        get {
            return this.backColorField;
        }
        set {
            this.backColorField = value;
        }
    }
    
    /// <remarks/>
    public int MaxMediaFolderSizeMB {
        get {
            return this.maxMediaFolderSizeMBField;
        }
        set {
            this.maxMediaFolderSizeMBField = value;
        }
    }
    
    /// <remarks/>
    public int DeleteFilesOlderThanDays {
        get {
            return this.deleteFilesOlderThanDaysField;
        }
        set {
            this.deleteFilesOlderThanDaysField = value;
        }
    }
    
    /// <remarks/>
    public string ServerAddress {
        get {
            return this.serverAddressField;
        }
        set {
            this.serverAddressField = value;
        }
    }
    
    /// <remarks/>
    public bool Enabled_ShowGettingStarted {
        get {
            return this.enabled_ShowGettingStartedField;
        }
        set {
            this.enabled_ShowGettingStartedField = value;
        }
    }
    
    /// <remarks/>
    public int Opacity {
        get {
            return this.opacityField;
        }
        set {
            this.opacityField = value;
        }
    }
    
    /// <remarks/>
    public int LANPort {
        get {
            return this.lANPortField;
        }
        set {
            this.lANPortField = value;
        }
    }
    
    /// <remarks/>
    public bool Enable_Storage_Management {
        get {
            return this.enable_Storage_ManagementField;
        }
        set {
            this.enable_Storage_ManagementField = value;
        }
    }
    
    /// <remarks/>
    public string FFMPEG_Camera {
        get {
            return this.fFMPEG_CameraField;
        }
        set {
            this.fFMPEG_CameraField = value;
        }
    }
    
    /// <remarks/>
    public string FFMPEG_Microphone {
        get {
            return this.fFMPEG_MicrophoneField;
        }
        set {
            this.fFMPEG_MicrophoneField = value;
        }
    }
    
    /// <remarks/>
    public string TimestampColor {
        get {
            return this.timestampColorField;
        }
        set {
            this.timestampColorField = value;
        }
    }
    
    /// <remarks/>
    public string BorderHighlightColor {
        get {
            return this.borderHighlightColorField;
        }
        set {
            this.borderHighlightColorField = value;
        }
    }
    
    /// <remarks/>
    public string BorderDefaultColor {
        get {
            return this.borderDefaultColorField;
        }
        set {
            this.borderDefaultColorField = value;
        }
    }
    
    /// <remarks/>
    public bool UseUPNP {
        get {
            return this.useUPNPField;
        }
        set {
            this.useUPNPField = value;
        }
    }
    
    /// <remarks/>
    public string YouTubeUsername {
        get {
            return this.youTubeUsernameField;
        }
        set {
            this.youTubeUsernameField = value;
        }
    }
    
    /// <remarks/>
    public string YouTubePassword {
        get {
            return this.youTubePasswordField;
        }
        set {
            this.youTubePasswordField = value;
        }
    }
    
    /// <remarks/>
    public string YouTubeAccount {
        get {
            return this.youTubeAccountField;
        }
        set {
            this.youTubeAccountField = value;
        }
    }
    
    /// <remarks/>
    public string YouTubeKey {
        get {
            return this.youTubeKeyField;
        }
        set {
            this.youTubeKeyField = value;
        }
    }
    
    /// <remarks/>
    public string YouTubeCategories {
        get {
            return this.youTubeCategoriesField;
        }
        set {
            this.youTubeCategoriesField = value;
        }
    }
    
    /// <remarks/>
    public string YouTubeDefaultCategory {
        get {
            return this.youTubeDefaultCategoryField;
        }
        set {
            this.youTubeDefaultCategoryField = value;
        }
    }
    
    /// <remarks/>
    public string YouTubeToken {
        get {
            return this.youTubeTokenField;
        }
        set {
            this.youTubeTokenField = value;
        }
    }
    
    /// <remarks/>
    public string CompressorOptions {
        get {
            return this.compressorOptionsField;
        }
        set {
            this.compressorOptionsField = value;
        }
    }
    
    /// <remarks/>
    public bool LogFFMPEGCommands {
        get {
            return this.logFFMPEGCommandsField;
        }
        set {
            this.logFFMPEGCommandsField = value;
        }
    }
    
    /// <remarks/>
    public bool BalloonTips {
        get {
            return this.balloonTipsField;
        }
        set {
            this.balloonTipsField = value;
        }
    }
    
    /// <remarks/>
    public string TrayIconText {
        get {
            return this.trayIconTextField;
        }
        set {
            this.trayIconTextField = value;
        }
    }
    
    /// <remarks/>
    public bool AutoLayout {
        get {
            return this.autoLayoutField;
        }
        set {
            this.autoLayoutField = value;
        }
    }
    
    /// <remarks/>
    public string UpnpDevice {
        get {
            return this.upnpDeviceField;
        }
        set {
            this.upnpDeviceField = value;
        }
    }
    
    /// <remarks/>
    public string IPMode {
        get {
            return this.iPModeField;
        }
        set {
            this.iPModeField = value;
        }
    }
    
    /// <remarks/>
    public string IPv4Address {
        get {
            return this.iPv4AddressField;
        }
        set {
            this.iPv4AddressField = value;
        }
    }
    
    /// <remarks/>
    public string IPv6Address {
        get {
            return this.iPv6AddressField;
        }
        set {
            this.iPv6AddressField = value;
        }
    }
    
    /// <remarks/>
    public bool SpecificIP {
        get {
            return this.specificIPField;
        }
        set {
            this.specificIPField = value;
        }
    }
    
    /// <remarks/>
    public bool DHCPReroute {
        get {
            return this.dHCPRerouteField;
        }
        set {
            this.dHCPRerouteField = value;
        }
    }
    
    /// <remarks/>
    public string MediaDirectory {
        get {
            return this.mediaDirectoryField;
        }
        set {
            this.mediaDirectoryField = value;
        }
    }
    
    /// <remarks/>
    public bool FFMPEG_SingleProcess {
        get {
            return this.fFMPEG_SingleProcessField;
        }
        set {
            this.fFMPEG_SingleProcessField = value;
        }
    }
    
    /// <remarks/>
    public bool Loopback {
        get {
            return this.loopbackField;
        }
        set {
            this.loopbackField = value;
        }
    }
    
    /// <remarks/>
    public int ServerReceiveTimeout {
        get {
            return this.serverReceiveTimeoutField;
        }
        set {
            this.serverReceiveTimeoutField = value;
        }
    }
    
    /// <remarks/>
    public int IPCameraTimeout {
        get {
            return this.iPCameraTimeoutField;
        }
        set {
            this.iPCameraTimeoutField = value;
        }
    }
    
    /// <remarks/>
    public string ServerName {
        get {
            return this.serverNameField;
        }
        set {
            this.serverNameField = value;
        }
    }
    
    /// <remarks/>
    public string UploadedVideos {
        get {
            return this.uploadedVideosField;
        }
        set {
            this.uploadedVideosField = value;
        }
    }
    
    /// <remarks/>
    public string Language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    public string RecentVLCList {
        get {
            return this.recentVLCListField;
        }
        set {
            this.recentVLCListField = value;
        }
    }
    
    /// <remarks/>
    public string VLCURL {
        get {
            return this.vLCURLField;
        }
        set {
            this.vLCURLField = value;
        }
    }
    
    /// <remarks/>
    public string VLCLocation {
        get {
            return this.vLCLocationField;
        }
        set {
            this.vLCLocationField = value;
        }
    }
    
    /// <remarks/>
    public bool AutoSchedule {
        get {
            return this.autoScheduleField;
        }
        set {
            this.autoScheduleField = value;
        }
    }
    
    /// <remarks/>
    public bool Fullscreen {
        get {
            return this.fullscreenField;
        }
        set {
            this.fullscreenField = value;
        }
    }
    
    /// <remarks/>
    public bool ShowStatus {
        get {
            return this.showStatusField;
        }
        set {
            this.showStatusField = value;
        }
    }
    
    /// <remarks/>
    public bool ShowToolbar {
        get {
            return this.showToolbarField;
        }
        set {
            this.showToolbarField = value;
        }
    }
    
    /// <remarks/>
    public bool ShowFileMenu {
        get {
            return this.showFileMenuField;
        }
        set {
            this.showFileMenuField = value;
        }
    }
    
    /// <remarks/>
    public bool AlwaysOnTop {
        get {
            return this.alwaysOnTopField;
        }
        set {
            this.alwaysOnTopField = value;
        }
    }
    
    /// <remarks/>
    public int LogFileSizeKB {
        get {
            return this.logFileSizeKBField;
        }
        set {
            this.logFileSizeKBField = value;
        }
    }
    
    /// <remarks/>
    public int CPUMax {
        get {
            return this.cPUMaxField;
        }
        set {
            this.cPUMaxField = value;
        }
    }
    
    /// <remarks/>
    public string AllowedIPList {
        get {
            return this.allowedIPListField;
        }
        set {
            this.allowedIPListField = value;
        }
    }
    
    /// <remarks/>
    public string Reseller {
        get {
            return this.resellerField;
        }
        set {
            this.resellerField = value;
        }
    }
    
    /// <remarks/>
    public bool CreateAlertWindows {
        get {
            return this.createAlertWindowsField;
        }
        set {
            this.createAlertWindowsField = value;
        }
    }
    
    /// <remarks/>
    public int MaxRedrawRate {
        get {
            return this.maxRedrawRateField;
        }
        set {
            this.maxRedrawRateField = value;
        }
    }
    
    /// <remarks/>
    public int PreviewItems {
        get {
            return this.previewItemsField;
        }
        set {
            this.previewItemsField = value;
        }
    }
    
    /// <remarks/>
    public bool ShowOverlayControls {
        get {
            return this.showOverlayControlsField;
        }
        set {
            this.showOverlayControlsField = value;
        }
    }
    
    /// <remarks/>
    public bool ShowMediaPanel {
        get {
            return this.showMediaPanelField;
        }
        set {
            this.showMediaPanelField = value;
        }
    }
    
    /// <remarks/>
    public int Priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    public bool Monitor {
        get {
            return this.monitorField;
        }
        set {
            this.monitorField = value;
        }
    }
    
    /// <remarks/>
    public int RunTimes {
        get {
            return this.runTimesField;
        }
        set {
            this.runTimesField = value;
        }
    }
    
    /// <remarks/>
    public bool ScreensaverWakeup {
        get {
            return this.screensaverWakeupField;
        }
        set {
            this.screensaverWakeupField = value;
        }
    }
    
    /// <remarks/>
    public string Vendor {
        get {
            return this.vendorField;
        }
        set {
            this.vendorField = value;
        }
    }
    
    /// <remarks/>
    public string TalkMic {
        get {
            return this.talkMicField;
        }
        set {
            this.talkMicField = value;
        }
    }
    
    /// <remarks/>
    public int PlaybackMode {
        get {
            return this.playbackModeField;
        }
        set {
            this.playbackModeField = value;
        }
    }
    
    /// <remarks/>
    public int JPEGQuality {
        get {
            return this.jPEGQualityField;
        }
        set {
            this.jPEGQualityField = value;
        }
    }
    
    /// <remarks/>
    public bool StopSavingOnStorageLimit {
        get {
            return this.stopSavingOnStorageLimitField;
        }
        set {
            this.stopSavingOnStorageLimitField = value;
        }
    }
    
    /// <remarks/>
    public bool ViewController {
        get {
            return this.viewControllerField;
        }
        set {
            this.viewControllerField = value;
        }
    }
    
    /// <remarks/>
    public int LayoutMode {
        get {
            return this.layoutModeField;
        }
        set {
            this.layoutModeField = value;
        }
    }
    
    /// <remarks/>
    public bool ShowPTZController {
        get {
            return this.showPTZControllerField;
        }
        set {
            this.showPTZControllerField = value;
        }
    }

    /// <remarks/>
    public bool ShowPTZCommandButtons
    {
        get
        {
            return this.showPTZCommandButtonsField;
        }
        set
        {
            this.showPTZCommandButtonsField = value;
        }
    }


    /// <remarks/>
    public bool BigButtons {
        get {
            return this.bigButtonsField;
        }
        set {
            this.bigButtonsField = value;
        }
    }
    
    /// <remarks/>
    public bool LockLayout {
        get {
            return this.lockLayoutField;
        }
        set {
            this.lockLayoutField = value;
        }
    }
    
    /// <remarks/>
    public string MediaPanelSize {
        get {
            return this.mediaPanelSizeField;
        }
        set {
            this.mediaPanelSizeField = value;
        }
    }
    
    /// <remarks/>
    public bool MinimiseOnClose {
        get {
            return this.minimiseOnCloseField;
        }
        set {
            this.minimiseOnCloseField = value;
        }
    }
    
    /// <remarks/>
    public bool IPv6Disabled {
        get {
            return this.iPv6DisabledField;
        }
        set {
            this.iPv6DisabledField = value;
        }
    }
    
    /// <remarks/>
    public bool DeleteToRecycleBin {
        get {
            return this.deleteToRecycleBinField;
        }
        set {
            this.deleteToRecycleBinField = value;
        }
    }
    
    /// <remarks/>
    public bool SpeechRecognition {
        get {
            return this.speechRecognitionField;
        }
        set {
            this.speechRecognitionField = value;
        }
    }
    
    /// <remarks/>
    public string DefaultManufacturer {
        get {
            return this.defaultManufacturerField;
        }
        set {
            this.defaultManufacturerField = value;
        }
    }
    
    /// <remarks/>
    public string AppendLinkText {
        get {
            return this.appendLinkTextField;
        }
        set {
            this.appendLinkTextField = value;
        }
    }
    
    /// <remarks/>
    public string StartupForm {
        get {
            return this.startupFormField;
        }
        set {
            this.startupFormField = value;
        }
    }
    
    /// <remarks/>
    public bool TrayOnMinimise {
        get {
            return this.trayOnMinimiseField;
        }
        set {
            this.trayOnMinimiseField = value;
        }
    }
    
    /// <remarks/>
    public bool EnableGZip {
        get {
            return this.enableGZipField;
        }
        set {
            this.enableGZipField = value;
        }
    }
    
    /// <remarks/>
    public long FeatureSet {
        get {
            return this.featureSetField;
        }
        set {
            this.featureSetField = value;
        }
    }
    
    /// <remarks/>
    public int MJPEGStreamInterval {
        get {
            return this.mJPEGStreamIntervalField;
        }
        set {
            this.mJPEGStreamIntervalField = value;
        }
    }
    
    /// <remarks/>
    public string AlertOnDisconnect {
        get {
            return this.alertOnDisconnectField;
        }
        set {
            this.alertOnDisconnectField = value;
        }
    }
    
    /// <remarks/>
    public string AlertOnReconnect {
        get {
            return this.alertOnReconnectField;
        }
        set {
            this.alertOnReconnectField = value;
        }
    }
    
    /// <remarks/>
    public int StartupMode {
        get {
            return this.startupModeField;
        }
        set {
            this.startupModeField = value;
        }
    }
    
    /// <remarks/>
    public int DisconnectNotificationDelay {
        get {
            return this.disconnectNotificationDelayField;
        }
        set {
            this.disconnectNotificationDelayField = value;
        }
    }
    
    /// <remarks/>
    public string Archive {
        get {
            return this.archiveField;
        }
        set {
            this.archiveField = value;
        }
    }
    
    /// <remarks/>
    public string ArchiveNew {
        get {
            return this.archiveNewField;
        }
        set {
            this.archiveNewField = value;
        }
    }
    
    /// <remarks/>
    public string MailAlertSubject {
        get {
            return this.mailAlertSubjectField;
        }
        set {
            this.mailAlertSubjectField = value;
        }
    }
    
    /// <remarks/>
    public string MailAlertBody {
        get {
            return this.mailAlertBodyField;
        }
        set {
            this.mailAlertBodyField = value;
        }
    }
    
    /// <remarks/>
    public string SMSAlert {
        get {
            return this.sMSAlertField;
        }
        set {
            this.sMSAlertField = value;
        }
    }
    
    /// <remarks/>
    public string SMTPFromAddress {
        get {
            return this.sMTPFromAddressField;
        }
        set {
            this.sMTPFromAddressField = value;
        }
    }
    
    /// <remarks/>
    public string SMTPUsername {
        get {
            return this.sMTPUsernameField;
        }
        set {
            this.sMTPUsernameField = value;
        }
    }
    
    /// <remarks/>
    public string SMTPPassword {
        get {
            return this.sMTPPasswordField;
        }
        set {
            this.sMTPPasswordField = value;
        }
    }
    
    /// <remarks/>
    public string SMTPServer {
        get {
            return this.sMTPServerField;
        }
        set {
            this.sMTPServerField = value;
        }
    }
    
    /// <remarks/>
    public int SMTPPort {
        get {
            return this.sMTPPortField;
        }
        set {
            this.sMTPPortField = value;
        }
    }
    
    /// <remarks/>
    public bool UseSMTP {
        get {
            return this.useSMTPField;
        }
        set {
            this.useSMTPField = value;
        }
    }
    
    /// <remarks/>
    public bool SMTPSSL {
        get {
            return this.sMTPSSLField;
        }
        set {
            this.sMTPSSLField = value;
        }
    }
    
    /// <remarks/>
    public bool DefaultRecordOnAlert {
        get {
            return this.defaultRecordOnAlertField;
        }
        set {
            this.defaultRecordOnAlertField = value;
        }
    }
    
    /// <remarks/>
    public bool DefaultRecordOnDetect {
        get {
            return this.defaultRecordOnDetectField;
        }
        set {
            this.defaultRecordOnDetectField = value;
        }
    }
    
    /// <remarks/>
    public bool FirstRun {
        get {
            return this.firstRunField;
        }
        set {
            this.firstRunField = value;
        }
    }
    
    /// <remarks/>
    public string DeviceDriverDefault {
        get {
            return this.deviceDriverDefaultField;
        }
        set {
            this.deviceDriverDefaultField = value;
        }
    }
    
    /// <remarks/>
    public string SSLCertificate {
        get {
            return this.sSLCertificateField;
        }
        set {
            this.sSLCertificateField = value;
        }
    }
    
    /// <remarks/>
    public bool SSLClientRequired {
        get {
            return this.sSLClientRequiredField;
        }
        set {
            this.sSLClientRequiredField = value;
        }
    }
    
    /// <remarks/>
    public bool SSLIgnoreErrors {
        get {
            return this.sSLIgnoreErrorsField;
        }
        set {
            this.sSLIgnoreErrorsField = value;
        }
    }
    
    /// <remarks/>
    public bool SSLCheckRevocation {
        get {
            return this.sSLCheckRevocationField;
        }
        set {
            this.sSLCheckRevocationField = value;
        }
    }
    
    /// <remarks/>
    public bool SSLEnabled {
        get {
            return this.sSLEnabledField;
        }
        set {
            this.sSLEnabledField = value;
        }
    }
    
    /// <remarks/>
    public string GoogleDriveConfig {
        get {
            return this.googleDriveConfigField;
        }
        set {
            this.googleDriveConfigField = value;
        }
    }
    
    /// <remarks/>
    public string DropBoxConfig {
        get {
            return this.dropBoxConfigField;
        }
        set {
            this.dropBoxConfigField = value;
        }
    }
    
    /// <remarks/>
    public bool OpenGrabs {
        get {
            return this.openGrabsField;
        }
        set {
            this.openGrabsField = value;
        }
    }
    
    /// <remarks/>
    public string TextSentences {
        get {
            return this.textSentencesField;
        }
        set {
            this.textSentencesField = value;
        }
    }
    
    /// <remarks/>
    public string PlayPaths {
        get {
            return this.playPathsField;
        }
        set {
            this.playPathsField = value;
        }
    }
    
    /// <remarks/>
    public int VLCFileCache {
        get {
            return this.vLCFileCacheField;
        }
        set {
            this.vLCFileCacheField = value;
        }
    }
    
    /// <remarks/>
    public string Referers {
        get {
            return this.referersField;
        }
        set {
            this.referersField = value;
        }
    }
    
    /// <remarks/>
    public string EncryptCode {
        get {
            return this.encryptCodeField;
        }
        set {
            this.encryptCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Tags {
        get {
            return this.tagsField;
        }
        set {
            this.tagsField = value;
        }
    }
    
    /// <remarks/>
    public int PortMapperMode {
        get {
            return this.portMapperModeField;
        }
        set {
            this.portMapperModeField = value;
        }
    }
    
    /// <remarks/>
    public int ArrangeMode {
        get {
            return this.arrangeModeField;
        }
        set {
            this.arrangeModeField = value;
        }
    }
    
    /// <remarks/>
    public string BrandPath {
        get {
            return this.brandPathField;
        }
        set {
            this.brandPathField = value;
        }
    }
    
    /// <remarks/>
    public configurationGPU GPU {
        get {
            return this.gPUField;
        }
        set {
            this.gPUField = value;
        }
    }
    
    /// <remarks/>
    public configurationLogging Logging {
        get {
            return this.loggingField;
        }
        set {
            this.loggingField = value;
        }
    }
    
    /// <remarks/>
    public configurationCloud Cloud {
        get {
            return this.cloudField;
        }
        set {
            this.cloudField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Server", IsNullable=false)]
    public configurationServer[] FTPServers {
        get {
            return this.fTPServersField;
        }
        set {
            this.fTPServersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Grid", IsNullable=false)]
    public configurationGrid[] GridViews {
        get {
            return this.gridViewsField;
        }
        set {
            this.gridViewsField = value;
        }
    }
    
    /// <remarks/>
    public configurationJoystick Joystick {
        get {
            return this.joystickField;
        }
        set {
            this.joystickField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Directory", IsNullable=false)]
    public configurationDirectory[] MediaDirectories {
        get {
            return this.mediaDirectoriesField;
        }
        set {
            this.mediaDirectoriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("group", IsNullable=false)]
    public configurationGroup[] Permissions {
        get {
            return this.permissionsField;
        }
        set {
            this.permissionsField = value;
        }
    }
    
    /// <remarks/>
    public string ChosenGroupName
    {
        get
        {
            return this.chosenGroupNameField;
        }
        set
        {
            this.chosenGroupNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class configurationGPU {
    
    private bool nVidiaField;
    
    private bool quickSyncField;
    
    private bool amdField;
    
    public configurationGPU() {
        this.nVidiaField = false;
        this.quickSyncField = false;
        this.amdField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool nVidia {
        get {
            return this.nVidiaField;
        }
        set {
            this.nVidiaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool QuickSync {
        get {
            return this.quickSyncField;
        }
        set {
            this.quickSyncField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool amd {
        get {
            return this.amdField;
        }
        set {
            this.amdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class configurationLogging {
    
    private int fileSizeField;
    
    private bool enabledField;
    
    private int keepDaysField;
    
    public configurationLogging() {
        this.fileSizeField = 100;
        this.enabledField = true;
        this.keepDaysField = 7;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(100)]
    public int FileSize {
        get {
            return this.fileSizeField;
        }
        set {
            this.fileSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool Enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(7)]
    public int KeepDays {
        get {
            return this.keepDaysField;
        }
        set {
            this.keepDaysField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class configurationCloud {
    
    private string dropBoxField;
    
    private string driveField;
    
    private string youTubeField;
    
    private string flickrField;
    
    private string oneDriveField;
    
    private string boxField;
    
    private string twitterField;
    
    public configurationCloud() {
        this.dropBoxField = "";
        this.driveField = "";
        this.youTubeField = "";
        this.flickrField = "";
        this.oneDriveField = "";
        this.boxField = "";
        this.twitterField = "";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string DropBox {
        get {
            return this.dropBoxField;
        }
        set {
            this.dropBoxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string Drive {
        get {
            return this.driveField;
        }
        set {
            this.driveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string YouTube {
        get {
            return this.youTubeField;
        }
        set {
            this.youTubeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string Flickr {
        get {
            return this.flickrField;
        }
        set {
            this.flickrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string OneDrive {
        get {
            return this.oneDriveField;
        }
        set {
            this.oneDriveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string Box {
        get {
            return this.boxField;
        }
        set {
            this.boxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string Twitter {
        get {
            return this.twitterField;
        }
        set {
            this.twitterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class configurationServer {
    
    private string nameField;
    
    private string serverField;
    
    private string usernameField;
    
    private string passwordField;
    
    private int portField;
    
    private bool usepassiveField;
    
    private bool sftpField;
    
    private bool renameField;
    
    private string identField;
    
    public configurationServer() {
        this.portField = 21;
        this.usepassiveField = false;
        this.sftpField = false;
        this.renameField = false;
        this.identField = "";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string server {
        get {
            return this.serverField;
        }
        set {
            this.serverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(21)]
    public int port {
        get {
            return this.portField;
        }
        set {
            this.portField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool usepassive {
        get {
            return this.usepassiveField;
        }
        set {
            this.usepassiveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool sftp {
        get {
            return this.sftpField;
        }
        set {
            this.sftpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool rename {
        get {
            return this.renameField;
        }
        set {
            this.renameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string ident {
        get {
            return this.identField;
        }
        set {
            this.identField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class configurationGrid {
    
    private configurationGridGridItem[] gridItemField;
    
    private string nameField;
    
    private int rowsField;
    
    private int columnsField;
    
    private bool fullScreenField;
    
    private bool alwaysOnTopField;
    
    private int framerateField;
    
    private string displayField;
    
    private int modeIndexField;
    
    private string modeConfigField;
    
    private bool fillField;
    
    private bool showAtStartupField;
    
    private bool overlaysField;
    
    public configurationGrid() {
        this.rowsField = 1;
        this.columnsField = 1;
        this.fullScreenField = true;
        this.alwaysOnTopField = false;
        this.framerateField = 5;
        this.displayField = "";
        this.modeIndexField = 0;
        this.modeConfigField = "";
        this.fillField = true;
        this.showAtStartupField = false;
        this.overlaysField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GridItem")]
    public configurationGridGridItem[] GridItem {
        get {
            return this.gridItemField;
        }
        set {
            this.gridItemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(1)]
    public int Rows {
        get {
            return this.rowsField;
        }
        set {
            this.rowsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(1)]
    public int Columns {
        get {
            return this.columnsField;
        }
        set {
            this.columnsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool FullScreen {
        get {
            return this.fullScreenField;
        }
        set {
            this.fullScreenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool AlwaysOnTop {
        get {
            return this.alwaysOnTopField;
        }
        set {
            this.alwaysOnTopField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(5)]
    public int Framerate {
        get {
            return this.framerateField;
        }
        set {
            this.framerateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string Display {
        get {
            return this.displayField;
        }
        set {
            this.displayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int ModeIndex {
        get {
            return this.modeIndexField;
        }
        set {
            this.modeIndexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string ModeConfig {
        get {
            return this.modeConfigField;
        }
        set {
            this.modeConfigField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool Fill {
        get {
            return this.fillField;
        }
        set {
            this.fillField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool ShowAtStartup {
        get {
            return this.showAtStartupField;
        }
        set {
            this.showAtStartupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool Overlays {
        get {
            return this.overlaysField;
        }
        set {
            this.overlaysField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class configurationGridGridItem {
    
    private configurationGridGridItemItem[] itemField;
    
    private int gridIndexField;
    
    private int cycleDelayField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Item")]
    public configurationGridGridItemItem[] Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int GridIndex {
        get {
            return this.gridIndexField;
        }
        set {
            this.gridIndexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int CycleDelay {
        get {
            return this.cycleDelayField;
        }
        set {
            this.cycleDelayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class configurationGridGridItemItem {
    
    private int typeIDField;
    
    private int objectIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int TypeID {
        get {
            return this.typeIDField;
        }
        set {
            this.typeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int ObjectID {
        get {
            return this.objectIDField;
        }
        set {
            this.objectIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class configurationJoystick {
    
    private string idField;
    
    private int xAxisField;
    
    private int centerXAxisField;
    
    private bool invertXAxisField;
    
    private int yAxisField;
    
    private int centerYAxisField;
    
    private bool invertYAxisField;
    
    private int zAxisField;
    
    private int centerZAxisField;
    
    private bool invertZAxisField;
    
    private int recordField;
    
    private int snapshotField;
    
    private int listenField;
    
    private int talkField;
    
    private int playField;
    
    private int stopField;
    
    private int nextField;
    
    private int previousField;
    
    private int maxMinField;

    private int ptSpeedProfileField;

    public configurationJoystick() {
        this.idField = "";
        this.xAxisField = 0;
        this.centerXAxisField = 0;
        this.invertXAxisField = false;
        this.yAxisField = 0;
        this.centerYAxisField = 0;
        this.invertYAxisField = false;
        this.zAxisField = 0;
        this.centerZAxisField = 0;
        this.invertZAxisField = false;
        this.recordField = 0;
        this.snapshotField = 0;
        this.listenField = 0;
        this.talkField = 0;
        this.playField = 0;
        this.stopField = 0;
        this.nextField = 0;
        this.previousField = 0;
        this.maxMinField = 0;
        this.ptSpeedProfileField = 0;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int XAxis {
        get {
            return this.xAxisField;
        }
        set {
            this.xAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int CenterXAxis {
        get {
            return this.centerXAxisField;
        }
        set {
            this.centerXAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool InvertXAxis {
        get {
            return this.invertXAxisField;
        }
        set {
            this.invertXAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int YAxis {
        get {
            return this.yAxisField;
        }
        set {
            this.yAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int CenterYAxis {
        get {
            return this.centerYAxisField;
        }
        set {
            this.centerYAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool InvertYAxis {
        get {
            return this.invertYAxisField;
        }
        set {
            this.invertYAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int ZAxis {
        get {
            return this.zAxisField;
        }
        set {
            this.zAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int CenterZAxis {
        get {
            return this.centerZAxisField;
        }
        set {
            this.centerZAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool InvertZAxis {
        get {
            return this.invertZAxisField;
        }
        set {
            this.invertZAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int Record {
        get {
            return this.recordField;
        }
        set {
            this.recordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int Snapshot {
        get {
            return this.snapshotField;
        }
        set {
            this.snapshotField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int Listen {
        get {
            return this.listenField;
        }
        set {
            this.listenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int Talk {
        get {
            return this.talkField;
        }
        set {
            this.talkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int Play {
        get {
            return this.playField;
        }
        set {
            this.playField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int Stop {
        get {
            return this.stopField;
        }
        set {
            this.stopField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int Next {
        get {
            return this.nextField;
        }
        set {
            this.nextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int Previous {
        get {
            return this.previousField;
        }
        set {
            this.previousField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int MaxMin {
        get {
            return this.maxMinField;
        }
        set {
            this.maxMinField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int PTSpeedProfile
    {
        get
        {
            return this.ptSpeedProfileField;
        }
        set
        {
            this.ptSpeedProfileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class configurationDirectory {
    
    private string entryField;
    
    private bool enable_Storage_ManagementField;
    
    private bool stopSavingOnStorageLimitField;
    
    private bool stopSavingFlagField;
    
    private int maxMediaFolderSizeMBField;
    
    private int deleteFilesOlderThanDaysField;
    
    private int idField;
    
    private bool archiveField;
    
    public configurationDirectory() {
        this.entryField = "NotSet";
        this.enable_Storage_ManagementField = false;
        this.stopSavingOnStorageLimitField = false;
        this.stopSavingFlagField = false;
        this.maxMediaFolderSizeMBField = 2000;
        this.deleteFilesOlderThanDaysField = 0;
        this.idField = 0;
        this.archiveField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("NotSet")]
    public string Entry {
        get {
            return this.entryField;
        }
        set {
            this.entryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Enable_Storage_Management {
        get {
            return this.enable_Storage_ManagementField;
        }
        set {
            this.enable_Storage_ManagementField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool StopSavingOnStorageLimit {
        get {
            return this.stopSavingOnStorageLimitField;
        }
        set {
            this.stopSavingOnStorageLimitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool StopSavingFlag {
        get {
            return this.stopSavingFlagField;
        }
        set {
            this.stopSavingFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(2000)]
    public int MaxMediaFolderSizeMB {
        get {
            return this.maxMediaFolderSizeMBField;
        }
        set {
            this.maxMediaFolderSizeMBField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int DeleteFilesOlderThanDays {
        get {
            return this.deleteFilesOlderThanDaysField;
        }
        set {
            this.deleteFilesOlderThanDaysField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool archive {
        get {
            return this.archiveField;
        }
        set {
            this.archiveField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class configurationGroup {
    
    private string nameField;
    
    private long featuresetField;
    
    private string passwordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long featureset {
        get {
            return this.featuresetField;
        }
        set {
            this.featuresetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
}

