//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8662
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class PTZSettings2 {
    
    private PTZSettings2Camera[] cameraField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Camera")]
    public PTZSettings2Camera[] Camera {
        get {
            return this.cameraField;
        }
        set {
            this.cameraField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PTZSettings2Camera {
    
    private PTZSettings2CameraMake[] makesField;
    
    private string commandURLField;
    
    private int portField;
    
    private bool portFieldSpecified;
    
    private bool pOSTField;
    
    private bool pOSTFieldSpecified;
    
    private string methodField;
    
    private string cookiesField;
    
    private PTZSettings2CameraCommands commandsField;
    
    private PTZSettings2CameraExtendedCommands extendedCommandsField;
    
    private string[] textField;
    
    private int idField;
    
    private string appendAuthField;
    
    public PTZSettings2Camera() {
        this.methodField = "GET";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Make", IsNullable=false)]
    public PTZSettings2CameraMake[] Makes {
        get {
            return this.makesField;
        }
        set {
            this.makesField = value;
        }
    }
    
    /// <remarks/>
    public string CommandURL {
        get {
            return this.commandURLField;
        }
        set {
            this.commandURLField = value;
        }
    }
    
    /// <remarks/>
    public int port {
        get {
            return this.portField;
        }
        set {
            this.portField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool portSpecified {
        get {
            return this.portFieldSpecified;
        }
        set {
            this.portFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool POST {
        get {
            return this.pOSTField;
        }
        set {
            this.pOSTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool POSTSpecified {
        get {
            return this.pOSTFieldSpecified;
        }
        set {
            this.pOSTFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Method {
        get {
            return this.methodField;
        }
        set {
            this.methodField = value;
        }
    }
    
    /// <remarks/>
    public string Cookies {
        get {
            return this.cookiesField;
        }
        set {
            this.cookiesField = value;
        }
    }
    
    /// <remarks/>
    public PTZSettings2CameraCommands Commands {
        get {
            return this.commandsField;
        }
        set {
            this.commandsField = value;
        }
    }
    
    /// <remarks/>
    public PTZSettings2CameraExtendedCommands ExtendedCommands {
        get {
            return this.extendedCommandsField;
        }
        set {
            this.extendedCommandsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AppendAuth {
        get {
            return this.appendAuthField;
        }
        set {
            this.appendAuthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PTZSettings2CameraMake {
    
    private string nameField;
    
    private string modelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Model {
        get {
            return this.modelField;
        }
        set {
            this.modelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PTZSettings2CameraCommands {
    
    private string centerField;
    
    private string leftField;
    
    private string leftUpField;
    
    private string rightField;
    
    private string rightUpField;
    
    private string upField;
    
    private string downField;
    
    private string leftDownField;
    
    private string rightDownField;
    
    private string stopField;
    
    private string zoomInField;
    
    private string zoomOutField;
    
    private string zoomInStopField;
    
    private string zoomOutStopField;
    
    /// <remarks/>
    public string Center {
        get {
            return this.centerField;
        }
        set {
            this.centerField = value;
        }
    }
    
    /// <remarks/>
    public string Left {
        get {
            return this.leftField;
        }
        set {
            this.leftField = value;
        }
    }
    
    /// <remarks/>
    public string LeftUp {
        get {
            return this.leftUpField;
        }
        set {
            this.leftUpField = value;
        }
    }
    
    /// <remarks/>
    public string Right {
        get {
            return this.rightField;
        }
        set {
            this.rightField = value;
        }
    }
    
    /// <remarks/>
    public string RightUp {
        get {
            return this.rightUpField;
        }
        set {
            this.rightUpField = value;
        }
    }
    
    /// <remarks/>
    public string Up {
        get {
            return this.upField;
        }
        set {
            this.upField = value;
        }
    }
    
    /// <remarks/>
    public string Down {
        get {
            return this.downField;
        }
        set {
            this.downField = value;
        }
    }
    
    /// <remarks/>
    public string LeftDown {
        get {
            return this.leftDownField;
        }
        set {
            this.leftDownField = value;
        }
    }
    
    /// <remarks/>
    public string RightDown {
        get {
            return this.rightDownField;
        }
        set {
            this.rightDownField = value;
        }
    }
    
    /// <remarks/>
    public string Stop {
        get {
            return this.stopField;
        }
        set {
            this.stopField = value;
        }
    }
    
    /// <remarks/>
    public string ZoomIn {
        get {
            return this.zoomInField;
        }
        set {
            this.zoomInField = value;
        }
    }
    
    /// <remarks/>
    public string ZoomOut {
        get {
            return this.zoomOutField;
        }
        set {
            this.zoomOutField = value;
        }
    }
    
    /// <remarks/>
    public string ZoomInStop {
        get {
            return this.zoomInStopField;
        }
        set {
            this.zoomInStopField = value;
        }
    }
    
    /// <remarks/>
    public string ZoomOutStop {
        get {
            return this.zoomOutStopField;
        }
        set {
            this.zoomOutStopField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PTZSettings2CameraExtendedCommands {
    
    private PTZSettings2CameraExtendedCommandsCommand[] commandField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Command")]
    public PTZSettings2CameraExtendedCommandsCommand[] Command {
        get {
            return this.commandField;
        }
        set {
            this.commandField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PTZSettings2CameraExtendedCommandsCommand {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
